language: php

matrix:
  include:
    - php: 7.4
      env: PHPUNIT_TEST=1

services:
  -  docker

before_install:
  - docker pull manticoresearch/manticore
  - docker network create manticore
  - docker run --rm --publish 9308:9308 --publish 9312:9312 --network manticore --name=manticoresearch-manticore --detach manticoresearch/manticore
  - docker run --rm --publish 19308:9308 --publish 19312:9312 --network manticore --name=manticoresearch-manticore-node --detach manticoresearch/manticore
  - docker ps
  - sudo apt update && sudo apt install php-json zip unzip git
env:
  global:
    - PHPSTAN_VERSION=^0.12
    - MS_HOST=127.0.0.1
    - MS_PORT=9308

before_script:
  - composer validate
  - if [[ $TRANSPORT ]]; then composer require php-http/discovery php-http/curl-client guzzlehttp/psr7 php-http/message http-interop/http-factory-guzzle; fi
  - if [[ $PHPSTAN_TEST ]]; then composer require --dev phpstan/phpstan && composer require php-http/discovery php-http/curl-client guzzlehttp/psr7 php-http/message http-interop/http-factory-guzzle; fi

install:
  # See https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes
  - composer global require hirak/prestissimo
  - composer install --prefer-dist

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit -d memory_limit=4G --filter=testJoin  test/; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit -d memory_limit=4G --coverage-clover=coverage.xml   test/   ; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=PSR2 src/ test/ ; fi
  - if [[ $PHPSTAN_TEST ]]; then vendor/bin/phpstan analyse --level=3 -c test/phpstan.neon src/; fi

after_script:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
